#!/bin/bash

cat \
	/system/ueventd*.rc /vendor/ueventd*.rc /system/etc/ueventd*.rc /vendor/etc/ueventd*.rc | \
	grep ^/dev | sed -e 's/^\/dev\///' | awk '{printf "ACTION==\"add\", KERNEL==\"%s\", OWNER=\"%s\", GROUP=\"%s\", MODE=\"%s\"\n",$1,$3,$4,$2}' | \
	sed -e 's/\r//' -e '/GROUP="radio"\|GROUP="root"\|GROUP="system"/!s/GROUP="\([^"]*\)"/GROUP="android_\1"/' \
> /etc/udev/rules.d/70-droidian.rules

udevadm trigger
